   
<img src='images/Pandas.png' alt = "Pandas" style="width:600; height:300"/>

# Exploratory Data Analysis (EDA)

Exploratory data analysis (EDA) is an approach used by data scientists to analyze and investigate data sets and summarize their main characteristics by using data visualization methods. In a simple form, the main purpose of EDA is to help look at data and see what it can tell us before making any assumptions. It can help identify obvious errors, as well as to understand patterns within the data, detect outliers (extreme values), and find interesting relations among the variables. For more information about Pandas Profiling Report check this [source](https://github.com/pandas-profiling/pandas-profiling).

## Working with Pandas Profiling

`pandas_profiling` is a Python module that extends the Pandas DataFrame with `df.profile_report()` for quick exploratory data analysis with just a few lines of code. In addition, it also generates interactive reports in web format with all the information easily available in the data. In summary, what pandas profiling does is save us all the work of visualizing and understanding the distribution of each variable. 

## Pandas Profiling installation

Open up your Anaconda Prompt or Terminal and run

`pip install ydata-profiling`. 

---

![](images/Pandas_profiling.png)

**Installing pandas-profiling**


## Importing Pandas Profiling

Like other libraries such as `numpy` or `pandas`, we also need to import pandas profiling after installation.

In [4]:
import numpy as np

import pandas as pd

from ydata_profiling import ProfileReport

# Example 1

Load the Ethiopian's flowers dataset(.csv) as `ethiopian_flower` DataFrame. The dataset is in the datasets folder.

In [2]:
ethiopian_flower = pd.read_csv("datasets/Ethiopian_flowers.csv")

We then use `.profile_report()` method on the DataFrame.

In [5]:
ethiopian_flower.profile_report()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 5/5 [00:00<00:00, 240.00it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

## Example 2

Load the `money_transfer_transactions.csv` data as `money_transfer` DataFrame. This data set is about money transaction in Uganda, Somalia, Kenya, Ethiopia South Sudan, Tanzania, and Rwanda. The dataset is in the datasets folder.

In [6]:
money_transfer =  pd.read_csv("datasets/money_transfer_transactions.csv")

We then use `.profile_report()` method on the DataFrame.

In [7]:
money_transfer.profile_report()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 10/10 [00:00<00:00, 501.24it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# Summarizing and Computing Descriptive Statistics

You can summarize your dataset with a set of common mathematical and statistical methods with Pandas attribute. For example, let's check the summary statistics in the `somalia_women` DataFrame. Using `.describe()` on an entire DataFrame we can get a summary of the distribution of continuous variables:

In [27]:
somalia_women = pd.read_csv("datasets/Somalian_women.csv")

somalia_women.head()

   height  weight
0     NaN    64.0
1    63.0    58.0
2    70.0    83.0
3    61.0     NaN
4    64.0    70.0

In [28]:
somalia_women.describe()

           height      weight
count  246.000000  245.000000
mean    64.715447   64.134694
std      4.429991   14.341639
min     58.000000   44.000000
25%     61.000000   52.000000
50%     65.000000   64.000000
75%     68.000000   75.000000
max     72.000000   93.000000

## Example 2

Consider `east_africa` DataFrame

In [29]:
east_africa = pd.read_csv("datasets/East-Africa-names.csv", encoding = "ISO-8859-1")

east_africa.head()

      Name Gender Origin.1  Origin.2  Origin.3 Origin.4
0   Aadaan      M   Somali       NaN       NaN      NaN
1    Aadam      M     Urdu    Somali  Estonian      NaN
2    Aaden      M   Somali       NaN       NaN      NaN
3  Aamiina      F   Somali       NaN       NaN      NaN
4   Abadir      M   Arabic  Bohairic   Sahidic      NaN

`.describe()` can also be used on a categorical variable to get the count of rows, unique count of categories, top category, and freq of top category. For example:

In [30]:
east_africa.describe()

          Name Gender Origin.1 Origin.2    Origin.3 Origin.4
count     1128   1128     1128      158          35       12
unique    1047      2       41       43          24        8
top     Ambesa      M  Amharic  Amharic  Indonesian   Somali
freq         3    614      242       39           4        2

In [31]:
registrations_dict = {
    "Gender": ["Male", "Female", "Female", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
"Country": ["Uganda", "Ethiopia", "Rwanda", "Somalia", "Sudan", "Kenya", "Uganda", "Kenya", "Somalia", "Rwanda"],
"Age": [11, 17, 15, 17, 13, 11, 9, 18, 13, 16]
}

registrations_df = pd.DataFrame(registrations_dict)

In [32]:
registrations_df

   Gender   Country  Age
0    Male    Uganda   11
1  Female  Ethiopia   17
2  Female    Rwanda   15
3  Female   Somalia   17
4    Male     Sudan   13
5  Female     Kenya   11
6    Male    Uganda    9
7  Female     Kenya   18
8    Male   Somalia   13
9  Female    Rwanda   16

In [33]:
registrations_df["Gender"].describe()

count         10
unique         2
top       Female
freq           6
Name: Gender, dtype: object

In [34]:
registrations_df.describe()

            Age
count  10.00000
mean   14.00000
std     3.05505
min     9.00000
25%    11.50000
50%    14.00000
75%    16.75000
max    18.00000

## Frequency distribution of Series
`.value_counts()` attribute can tell us the frequency distribution of all values in a column or Series. To illustrate these, consider examples below:

## Example 1

In [35]:
registrations_df["Gender"].value_counts()

Female    6
Male      4
Name: Gender, dtype: int64

## Example 2

Consider `east_africa` names DataFrame, what is the distribution of male and female in the `Gender` column?

In [36]:
east_africa.head()

      Name Gender Origin.1  Origin.2  Origin.3 Origin.4
0   Aadaan      M   Somali       NaN       NaN      NaN
1    Aadam      M     Urdu    Somali  Estonian      NaN
2    Aaden      M   Somali       NaN       NaN      NaN
3  Aamiina      F   Somali       NaN       NaN      NaN
4   Abadir      M   Arabic  Bohairic   Sahidic      NaN

In [37]:
east_africa["Gender"].value_counts()

M    614
F    514
Name: Gender, dtype: int64

As you can see, there are $616$ and $515$ male and female names respectively.

`.value_counts()` also accepts some other arguments i.e. `sort = True/False` and `normalize = True/False`. The Series is sorted by value in descending order with `sort = True` and relative frequecies with 
`normalize = True`.

In [39]:
east_africa["Gender"].value_counts(normalize = True)*100

M    54.432624
F    45.567376
Name: Gender, dtype: float64

In [42]:
east_africa["Gender"].value_counts(sort = True, normalize = True)

M    0.544326
F    0.455674
Name: Gender, dtype: float64

You can get the result in percentage by multiplying by 100

In [173]:
east_africa["Gender"].value_counts(sort = True, normalize = True) * 100

M    54.432624
F    45.567376
Name: Gender, dtype: float64